In [19]:
import pandas as pd
import numpy as np

In [20]:
df  = pd.read_csv('People Data.csv')

In [21]:
type(df)

pandas.core.frame.DataFrame

In [22]:
list(df.columns)

['Index',
 'User Id',
 'First Name',
 'Last Name',
 'Gender',
 'Email',
 'Phone',
 'Date of birth',
 'Job Title',
 'Salary']

In [23]:
df.head()

Index          User Id First Name Last Name  Gender  \
0      1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1      2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2      3  810Ce0F276Badec     Sheryl    Lowery  Female   
3      4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4      5  9afFEafAe1CBBB9    Lindsey      Rice  Female   

                           Email               Phone Date of birth  \
0            pwarner@example.org        857.139.8239    27-01-2014   
1  fergusonkatherine@example.net                 NaN    26-07-1931   
2            fhoward@example.org       (599)782-0605    25-11-2013   
3          zjohnston@example.com                 NaN    17-11-2012   
4               elin@example.net  (390)417-1635x3010    15-04-1923   

                  Job Title  Salary  
0         Probation officer   90000  
1                    Dancer   80000  
2                      Copy   50000  
3  Counselling psychologist   65000  
4       Biomedical engineer  100000

In [25]:
df.tail()

Index          User Id First Name Last Name  Gender  \
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                       Email                  Phone Date of birth  \
995   lyonsdaisy@example.net           021.775.2933    05-01-1959   
996  dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997   georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998      wanda04@example.net          (915)292-2254    31-08-1971   
999  deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000

In [26]:
df.dtypes

Index             int64
User Id          object
First Name       object
Last Name        object
Gender           object
Email            object
Phone            object
Date of birth    object
Job Title        object
Salary            int64
dtype: object

# 1. Demonstrate three different methods for creating identical 2D arrays in NumPy ,Provide the code for each method and the final output after each method

In [29]:
### Method - 01 , Identical 2D Array
first_array = np.array([[11, 22, 33], [44, 55, 66]])
first_array

array([[11, 22, 33],
       [44, 55, 66]])

In [30]:
### Method - 02 , Identical 2D Array
second_array = np.ones((2, 3), dtype=int)
second_array[0] = [11, 22, 33]
second_array[1] = [44, 55, 66]
second_array

array([[11, 22, 33],
       [44, 55, 66]])

In [31]:
### Method - 03 , Identical 2D Array
third_array = np.zeros((2, 3), dtype=int)
third_array[0] = [11, 22, 33]
third_array[1] = [44, 55, 66]
third_array

array([[11, 22, 33],
       [44, 55, 66]])

# 2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 100 and Reshape that 1D array into a 2D array .

In [32]:
### np -  We have already imported in a first line
array_1d = np.linspace(1, 100, 100)
array_1d

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [33]:
# Applying re-shape into 2d array
array_2d = array_1d.reshape(10, 10)
array_2d

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

# 3. Explain the following terms :
a. The difference in np.array, np.asarray and np.asanyarray.

Ans - >

np.array 

1. Always creates a new array.
2. Copies the data unless explicitly specified not to.
3. Converts any input to a base ndarray.

np.asarray

1. Avoids copying if the input is already an array of the same dtype.
2. Converts the input to a base ndarray without unnecessary data copying.

np.asanyarray

1. Similar to np.asarray(), but preserves subclasses of ndarray.
2. Converts the input to an array while keeping any subclass type.


b. The difference between Deep copy and shallow copy.

Deep Copy

1. Recursively copies all objects found in the original.
2. Creates entirely independent copies of both the top-level structure and all nested objects.
3. Changes to nested objects in the deep copy do not affect the original.


 Shallow Copy

1. Copies the top-level structure.
2. Does not create copies of nested objects; instead, it references the same nested objects as the original.
3. Changes to nested objects affect both the original and the shallow copy.


### Below is example of deep copy and shallow copy

In [34]:
arr = [10,20,30,40]
arr

[10, 20, 30, 40]

In [36]:
### This is example of deep copy
b = np.copy(arr)
b[0] = 234
b

array([234,  20,  30,  40])

In [37]:
### This is example of shallow copy
a = arr
arr[0] = 100
arr

[100, 20, 30, 40]

# 4. Generate a 3*3 array with random floating-point numbers between 5 and 20 . Then, round each number in the array to 2 decimal places.

# 5. Create a NumPy array with random integers between 1 and 10 of shape(5,6).
After creating the array perform the following operations:

a)Extract all even integers from array.

b)Extract all odd integers from array.

# 6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10.Perform the following operations:

a) Find the indices of the maximum values along each depth level (third axis).

b) Perform element-wise multiplication of between both array.

# 7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.

# 8.Perform the following tasks using people dataset:

 a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’' column as a Series and display its last 5 values.

# 9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and ‘Salary’ should Pe less than 85000.

# 10. Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6 ?

# 11. Create two different Series, each of length 50, with the following criteria:

a) The first Series should contain random numbers ranging from 10 to 50.

b) The second Series should contain random numbers ranging from 100 to 1000.

c) Create a DataFrame by joining these Series by column, and, change the names of the columns to 'col1', 'col2',
etc.

# 12. Perform the following operations using people data set:

a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

b) Delete the rows containing any missing values.

d) Print the final outut also.

# 13. Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the
following tasks using Matplotlib and NumPy:

a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.

b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.

f) Display a legend for the scatter plot, the horizontal line, and the vertical line.

# 14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and
Perform the following tasks using Matplotlib:

a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the plot as 'Temperature and Humidity Over Time'.

# 15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib:

a) Plot a histogram of the data with 30 bins.

b) Overlay a line plot representing the normal distribution's probability density function (PDF).

c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

d) Set the title of the plot as 'Histogram with PDF Overlay'.

# 16. Set the title of the plot as 'Histogram with PDF Overlay'.

# 17. Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.

# 18. With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine Wave Function'.

# 19. Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'.

# 20. Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'.

# 21. Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set the title as 'Interactive Pie Chart'.